#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch case.foam

runApplication surfaceFeatureExtract

runApplication blockMesh


runApplication snappyHexMesh -overwrite 

restore0Dir

runApplication potentialFoam -writep

#------------------------------------------------------------------------------
