#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


touch case.foam

surfaceFeatureExtract


blockMesh


#decomposePar

#mpirun -np 8  snappyHexMesh -overwrite -parallel
snappyHexMesh -overwrite 

#reconstructParMesh -constant

mkdir 0

cp 0.orig/* 0

 setFields

#decomposePar 

#mpirun -np 8 interFoam -parallel >run.log&

#------------------------------------------------------------------------------
