#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch case.foam

surfaceFeatureExtract

blockMesh


snappyHexMesh -overwrite 

mkdir 0

cp 0.orig/* 0

potentialFoam -writep

#------------------------------------------------------------------------------
